### ISSUE TITLE
Problem with docker container

### ISSUE THREAD

**Issue by tran1903** [xphongvn/rlcomp2020#10]
Nothing in the v folder. Why? I am using macOS. I already pointed to the right folder.
Thanks for all helps.
![Screen Shot 2020-08-08 at 9 02 54 AM](https://user-images.githubusercontent.com/69374694/89700161-13c03580-d956-11ea-82cd-d66f6ffcd178.png)

**Comment by thotho** [comment]
You have to bind you working directory to docker container volume using:
`-v {Your working directory}:/v`
Please make sure **{Your working directory}** is correct.
For example, you put all your source code in "**D:\Project**"
Then, the command should be: `-v D:\Project:/v`
If you need more help, please send email to support.ailab@fsoft.com.vn
Regards,

**Comment by tran1903** [comment]
I already did that. But no help.

**Comment by thotho** [comment]
Can you send your email address?
I will contact you.

**Comment by tran1903** [comment]
Yes, ggcloudplatform@gmail.com
Regards.

**Comment by thotho** [comment]
Please check you mailbox.
I will support via email, then I will close this issue.
Thanks,
