### ISSUE TITLE
Viết sai vòng lặp 

### ISSUE THREAD

**Issue by freedom1810** [xphongvn/rlcomp2020#11]
https://github.com/xphongvn/rlcomp2020/blob/94e4834461137b2bd0c64a35b242546cafa1f10b/Miner-Training-Local-CodeSample/MINER_STATE.py#L112-L127

trong đoạn code này dòng 124 đã khai báo ``` self.players = new_state["players"]  ``` thì len(slelf.players) luôn bằng 4 rồi thì đoạn lệnh for bên dưới em thấy không bao giờ được thưc hiện cả

**Comment by thotho** [comment]
Đấy là ở môi trường training của bạn thôi nhé, trên thực tế có thể sẽ có những trận không đủ 4 người chơi vì một vài lý do nào đó.
Ngoài ra, trận verify của bạn khi submit code bạn sẽ chỉ đấu 1 mình thôi nhé.
