### ISSUE TITLE
Can't connect socket MinerEnv

### ISSUE THREAD

**Issue by duclinhfetel** [xphongvn/rlcomp2020#12]
When I run source code at Miner-Testing-CodeSample (latest branch master). 
```
python3 TestingAgent.py 
```
I got a message:
![image](https://user-images.githubusercontent.com/20751859/89790505-387dfe00-db4c-11ea-8728-088e0207cf8b.png)

Could anyone help me to solve it?
Thanks.

**Comment by thotho** [comment]
Did you start server?

**Comment by duclinhfetel** [comment]
> Did you start server?

I didn't.
ah. Do I need to run DUMMY_SERVER.py at Miner-Testing-Server?

**Comment by duclinhfetel** [comment]
> > Did you start server?
> 
> I didn't.
> ah. Do I need to run DUMMY_SERVER.py at Miner-Testing-Server?

I fixed this problem. thanks.
