### ISSUE TITLE
Incorrect numpy version?

### ISSUE THREAD

**Issue by tran1903** [xphongvn/rlcomp2020#13]
ERROR: No matching distribution found for numpy==1.18.4
I got this error when I install the library for my 2nd computer.

**Comment by thotho** [comment]
Which OS are you using? Is it same as the 1st one?
Can you install the lib on the 1st one?

**Comment by tran1903** [comment]
Yes, I am using macOS.

**Comment by thotho** [comment]
Did you update pip version? 
python3 -m pip install --upgrade pip

**Comment by tran1903** [comment]
Yes, i did.

**Comment by thotho** [comment]
Because you have installed successfully on your 1st pc, then no problem with lib version.
I will close this issue and support you via email.
Please check your mailbox.
Regards,
