### ISSUE TITLE
Issue when client update new state

### ISSUE THREAD

**Issue by quan5609** [xphongvn/rlcomp2020#4]
I found a problem in the function update_state() in MINER_STATE.py in folder Miner-Testing-CodeSample:
![bug](https://user-images.githubusercontent.com/50260806/89094617-fc31fb80-d3ef-11ea-94d9-aa2f4275bcaa.png)

**Why you set self.players = new_state["players"] then again append 4 times its position to self.players?**

**Comment by thotho** [comment]
We don't append 4 times to self.players, but just make sure there are always 4 players in sample training model.
The loop is for appending new dummy players to self.players if len(self.players) < 4.
Of course, you can modify the code, if your training strategy is different.
Thanks for your comment.
