### ISSUE TITLE
Problem with create and run docker container 

### ISSUE THREAD

**Issue by Mailfox97** [xphongvn/rlcomp2020#9]
![Untitled](https://user-images.githubusercontent.com/50673953/89520887-bf5b6f80-d808-11ea-8467-dc4e342cd367.png)
Hi everyone,
My prolem is when i create and run docker container follow instruction in this github, there are no files in my container.
Beside, there is just 1 container created stead of 2 container like in the construction. 
I use Window 10 OS.
I don't know what's problem with this, i tried many times but the result is still the same!
Please help me, thanks.

**Comment by thotho** [comment]
I saw that, your working directory is "D:\Desktop\GoldMinerAI\rlcomp2020\Miner-Training-Local-CodeSample"
But in the command, you are missing "**\rlcomp2020**"

**Comment by Mailfox97** [comment]
> I saw that, your working directory is "D:\Desktop\GoldMinerAI\rlcomp2020\Miner-Training-Local-CodeSample"
> But in the command, you are missing "**\rlcomp2020**"

I have another path without "\rlcomp2020" in my pc so it's not problem, thank you for your reply!

**Comment by thotho** [comment]
If you need more help, please send you email address.
I will contact and support you via email.
Thanks,

**Comment by Mailfox97** [comment]
> If you need more help, please send you email address.
> I will contact and support you via email.
> Thanks,

Thank you! This is my email : nttn.love.waffle@gmail.com

**Comment by thotho** [comment]
Please check your mailbox.
I will support you via email, then I will close this issue.
Thanks,

**Comment by Mailfox97** [comment]
> Please check your mailbox.
> I will support you via email, then I will close this issue.
> Thanks,

Ok, i've just replied your email
